CREATE TABLE synopsis (
      synopsis_id serial NOT NULL PRIMARY KEY,
      serie_id serial,
      body text,
      FOREIGN KEY (serie_id) REFERENCES serie (serie_id)
);

INSERT INTO synopsis (serie_id, body) VALUES
(1, 'Clyde, un jeune homme naïf, s''est donné pour objectif de trouver la pierre du Destin, un objet mythique, en hommage à son grand-père décédé. Mais alors qu''il travaille en tant que soldat dans l''équipage d''un vaisseau de marchandises, ce dernier est pris d''assaut par le général Holista, un célèbre commandant d''armée. Clyde réussit, par miracle, à échapper au désastre en prenant la fuite à bord de Brodog, une frégate volante.' ),
(2, 'Une compagnie constituée de personnages tous plus imbéciles les uns que les autres va s''aventurer dans un donjon mystérieux pour aller chercher une statuette mystérieuse et ensuite la remettre à un commanditaire mystérieux, en échange de 8000 pièces d''or. Mais cette quête s''avérera bien plus difficile que prévu...'),
(3, 'Une équipe de sauvetage est envoyée avec un vaisseau spatial à proximité de la planète Adoprixtoxis, afin de récupérer l''équipage d''un vaisseau cargo (transportant des yoyos) en péril. Abattue par un trou noir, ses membres s''écrasent sur la planète qu''ils survolaient, Adoprixtoxis... Cette planète aux abords hostiles se révèlera pleine de surprises.'),
(4, 'L''équipage d''un vaisseau découvre une capsule de sauvetage à la dérive dans l''espace depuis des siècles. Le contenu de cette capsule va les entraîner malgré eux sur la piste d''un des plus grands mystères de la galaxie : Xantah, l''astre de légende.'),
(5, 'Wrandrall cherche désespérément des compagnons de route pour sa quête : ils devront braver vents et marées pour aller explorer une grotte. Nul ne sait ce qui les attend sur cette route, ni ce qu''ils trouveront au fond de cette grotte… Une seule chose est sûre, c''est qu''ils n''ont aucune idée de ce dans quoi ils se sont embarqués.'),
(6, 'SURVIVAURE, une grande saga d''aventures spatiales démentielles, au delà des limites connues de l''espace. Ça se passe donc dans le futur, avec des vaisseaux qui font «wizzzz», des droïdes stupides qui font «bip» et des créatures extraterrestres qui auraient mieux fait de ne pas se commettre dans SURVIVAURE. De l''action, du suspense, de l''amour, du poulet, des crêpes au fromage, une quête sans merci, à lire chez vous sans chaussettes et mal rasé. La saga spatiale du millénaire : SURVIVAURE !!'),
(7, 'Une agence d''espionnage recrute l''Agent 0 et lui confie un gadget ultra-moderne pour mener à bien les missions dont il a la charge. Cependant, l''Agent 0 n''a pas les meilleures capacités en tant que membre de l''Agence. Un jour emprisonné, il est libéré par un adolescent sous condition de l''accompagner dans ses missions.'),
(8, 'Lucas Salpêtrière est un jeune homme à l''imagination débordante. Depuis qu''il est tout petit, il échappe à sa morne réalité quotidienne et à ses divers tracas (comme son boulot ou sa petite amie) en se réfugiant dans son monde imaginaire : Trimoria'),
(9, 'Alors que les cyber-technologies poursuivent leurs avancées, Une société scientifique du nom de Gamelife a réalisé un tour de force, que l’on croyait impossible jusqu’alors : connecter intégralement un humain a un monde virtuel, grâce aux travaux d’un éminent chercheur'),
(10, 'Le Chasseur est une fiction sonore en 21 épisodes publiés en temps réel. Elle s''intègre dans l''univers "Chroniques de la Terre Gelée" créé par Valkyria (a.k.a. Tristan Lohengrin) et François TJP'),
(11, 'A quel endroit vous réfugieriez vous dans le cas où le monde que vous connaissez ne soit plus un endroit sùr ? Si vous ne pouviez plus faire confiance à personne, si tant est qu''il y ait encore quelqu''un en vie ? Dans votre appartement ? C''est le choix que j''ai fait, et je ne le regrette pas, pour l''instant. Quand on trouve un dictaphone et qu''on est seul ... on fini par lui parler comme à son chat, ça occupe l''esprit.'),
(12, 'Super-Vilain et génie du mal en pleine dépression, le Docteur Bonobo est en mal de conquête mondiale et d''asservissement des peuples. Pour arriver à son but il s''est entouré d''une armée de clones (une de ses nombreuses créations), et de précieux alliés de tous horizons. Mais conquérir le monde n''est pas chose aisée et le Docteur l''apprendra à ses dépend durant sa quête de pouvoir.'),
(13, 'Deux frères pourfendeurs, chasseurs de monstres, les deux frères ne chassent pas comme des pourfendeurs lambdas, ils hypnotisent les monstres en chanson ...'),
(14, 'À qui m’entendrait, à qui voudrait m’entendre. Je sors difficilement de l’obscurité comme, comme on se réveille d’un trop long sommeil. Malgré mon crâne endolori et le battement incessant de mon coeur, quelques souvenirs reviennent... comme des flashs. Comme le veut la procédure, j’enregistre ce journal. Il permettra d’organiser les fragments de mémoire, les réminiscences vagues des évènements de ces derniers jours, ou semaines... Il arrivera peut être à expliquer ce que je ne parviens à comprendre. Comment j’en suis arrivé là. Comment je me retrouve condamné dans cette capsule de sauvetage. Dérivant indéfiniment dans le vide spatial. Comme une bouteille à la mer.'),
(15, 'une jeune étudiante se réveille après 8000 ans de cryogénisation dans un univers ou l''humanité n''a plus sa place '),

(16, 'Dans une galaxie en reconstruction, le capitaine Délisse, dernier homme vivant, survit en tant que convoyeur. Sur Seyten, une nouvelle mission lui est confiée par le grand Omgaa, caïd local. Amener des armes sur la planète Anef… Mais une jeune Néfil décide de s’inviter à bord du Belbeth System. Pour une raison bien particulière : sauver le capitaine d’un danger proche.'),
(17, 'Retrouver un journal de bord enfoui sous les mers ou perdu dans l''espace, donne un lien temporel unique avec son capitaine et ses péripéties. Il s''agit le plus souvent d''un lien vers le passé. Mais il arrive que l''on retrouve, par le biais de fictions, des journaux offrant un lien temporel avec le futur, ou du moins avec quelque chose qui y ressemble. C’est le cas des enregistrements audio du Docteur Ambrosia qui, depuis la station sous-marine Poséidôme, y a retranscrit ses activités avec la faune des profondeurs.'),
(18, 'Printemps de l''an de grâce 1680, John B., un pirate prétendument anglais, part à la recherche d’un mystérieux cacao après que sa prisonnière, l''experte en chocolat Philomène Ganache, lui a révélé son existence. Au cours de leurs aventures, ils se confrontent à de nombreux adversaires qui, tous, convoitent également ce cacao pour en percer le secret.'),
(19, 'Charles-Edouard Fitzgerald, jeune lutin dragueur et fainéant, s''apprête à voir sa vie changer du tout au tout, lorsque le Roi du Royaume de la Poudre d''Escampette (et oui, nous sommes dans un monde de contes de fées) annonce dans une lettre que tous les chômeurs du Royaume doivent impérativement se rendre au camp militaire d’entraînement.'),
(20, 'Thomas, un jeune homme sans énergie ni charisme, reçoit la visite d''un robot, Eliott. Ensemble, ils partent dans une folle aventure à travers le temps à la recherche d''Iris, l''ex-petite amie de Thomas, et du père de celle-ci, un scientifique mystérieux.'),
(21, 'Chris et Ézéchiel sont enfermés à l''asile, l''un pour une soit disant dépression et l''autre pour un syndrome paranoïaque. Une occasion en or créée par un autre pensionnaire, un certain Lucas Salpetrière, va leur permettre de s''échapper.'),
(22, 'Ce n''est pas une saga mais un ensemble de monos individuels. L''univers de Trimoria fait quelques apparitions dans Trimoria TV.'),
(23, ' Remi est un enfant de huit ans, pauvre orphelin (son père est mort 3 fois environ) qui parcourt le monde à la recherche d’un foyer, de nourriture, et d’amis. Des amis, justement, il en trouve en la compagnie d’animaux dont le destin est plutôt… tragique, entres autres par la faute du jeune garçon qui a tendance à les sacrifier pour sauver sa peau… Parce que oui, Remi à la fâcheuse tendance de se mettre dans des situations pour le moins inconfortables… voire carrément mortelles !'),
(24, 'Quelque part, en pleine campagne, un routier s''arrête dans un restaurant, car il a une faim de loup, mais alors qu’il commence à déguster son repas, il ne se doute pas qu’une si petite envie peut faire basculer le sort de l’humanité…'),
(25, 'En 2074, le monde est pourri par la société de consommation et la technologie grandissante. Daniel Dawson n''attend plus rien de la vie. Se retrouvant par mégarde au mauvais endroit et au mauvais moment, il est témoin d''un accident scientifique. Sa vie s''en retrouvera changée à jamais...'),
(26, 'Wallace Ticot, psycologue excentrique, décide d''enregistrer les délires de ses patients.'),
(27, 'Arthur Accroc, terrien, apprends un jeudi que sa planète est sur le point d''être détruite pour laisser place à une autoroute hyper-spatiale. Il apprends également le même jour que son meilleur ami, Ford, n''est pas terrien mais originaire d''une petite planète près de Bételgeuse et qu''il est sur Terre pour une mission d''étude afin de compléter le livre sur lequel il travaille'),
(28, 'Un jeune homme se réveille après un an de coma. depuis le monde à bien changé. il faudra l''accepter'),
(29, 'Des capsules de Science-Fiction Radiophonique qui vous racontent simplement... la Fin du Monde.'),
(30, 'Pour que la beauté d''une rose illumine, nous devenons les serviteurs de ses épines... Laissez-vous transporter dans le monde merveilleux et troublé de Ozion , une fiction sonore... magique !'),
(31, 'La société Synergy ayant implanté la base de recherche Eternity sur la planète mars, ne reçoit plus de nouvelle de leur structure depuis plus d''un an, suite à l''ouverture d''une faille dimensionnelle dirigée vers les enfers, libérant des démons ravageant toute la base. Cependant un groupe de survivants tente encore de s''échapper d''Eternity encore infesté de monstres. Ils vont faire la rencontre d''une arme vivante qui s''est activé et qui a pour mission de fermer la faille vers le monde des enfers'),
(32, 'C''était un jour, on était au bistro avec Phil, on buvait des coups. Quand soudain…'),
(33, 'un duo "d''aide criminelle" a pour boulot d''aider les malfrats en difficulté dans leur triste besogne, pour leur propre société : La Main Sur le Corps... Un tueur n''arrive pas à découpé sa victime ? il appelle La Main sur le Corps. Un type vient de tuer plein de gens et ne sait pas quoi faire des cadavres ? Il appelle La Main sur le Corps.'),
(34, ' Je comprends pas. J''entends juste ce Zzap partout. Il me suit. Mais d''où il vient ? Pourquoi y a que moi qui l’entend ? Qu''est ce qu''il se passe bordel ?! '),
(35, 'N''essayez pas de régler votre lecteur. Nous contrôlons à présent ce que vous entendrez et imaginerez. Vous entrez dans une dimension au-delà du réel, où le sens de la vue, ne vous sera d''aucune aide. Une dimension qui se trouve partout autour de vous, et qui se manifeste dans votre quotidien. Faites entièrement confiance en votre ouïe, vous entrez,... Dans la Blind ZONE'),
(36, 'Bienvenue dans l''imaginarium, un monde imaginaire géré grâce à une règle fondamentale, le son. Et c''est vous auditeurs, en interprétant ces sons qui allez faire vivre ce monde. Notre but en temps qu''expéditeurs, est de vous initier à ça et de vous emmener jusqu''au mur de l''imaginarium, la frontière de ce monde incroyable. Pour ce faire nous allons passer par différents endroits, différentes villes construites par Onhera et par les architectes de ce monde. Mais nous risquerons d''avoir quelques...'),
(37, 'En 2082, posséder une biopuce est un luxe si l''on ne veut pas devenir un dégène. Coup de chance, c''est une invention de mon père et il a été assez sympa pour nous en installer une à John Malkovitche et moi. John Malkovitche ? C''est mon chat. Un des derniers d''ailleurs, car les animaux ont disparu depuis la grande guerre génétique. Heureusement pour un biologiste comme moi, il reste des végétaux mutants à étudier. Que demander de plus ? Un grand labo sécurisé ? C''est fait. Des amis ? C''est fait aussi, mais je vous en parlerai ne vous inquiétez pas !'),
(38, 'Retrouvez Lara, Dundee, Flagada et plein d''autres aventuriers dans cette saga MP3 du studio TJP.'),
(39, 'Blind cowboy, le premier western audio !')




