CREATE TABLE synopsis (
      synopsis_id serial NOT NULL PRIMARY KEY,
      serie_id serial,
      body text,
      FOREIGN KEY (serie_id) REFERENCES serie (serie_id)
);

INSERT INTO synopsis (serie_id, body) VALUES
(1, 'Clyde, un jeune homme naïf, s''est donné pour objectif de trouver la pierre du Destin, un objet mythique, en hommage à son grand-père décédé. Mais alors qu''il travaille en tant que soldat dans l''équipage d''un vaisseau de marchandises, ce dernier est pris d''assaut par le général Holista, un célèbre commandant d''armée. Clyde réussit, par miracle, à échapper au désastre en prenant la fuite à bord de Brodog, une frégate volante.' ),
(2, 'Une compagnie constituée de personnages tous plus imbéciles les uns que les autres va s''aventurer dans un donjon mystérieux pour aller chercher une statuette mystérieuse et ensuite la remettre à un commanditaire mystérieux, en échange de 8000 pièces d''or. Mais cette quête s''avérera bien plus difficile que prévu...'),
(3, 'Une équipe de sauvetage est envoyée avec un vaisseau spatial à proximité de la planète Adoprixtoxis, afin de récupérer l''équipage d''un vaisseau cargo (transportant des yoyos) en péril. Abattue par un trou noir, ses membres s''écrasent sur la planète qu''ils survolaient, Adoprixtoxis... Cette planète aux abords hostiles se révèlera pleine de surprises.'),
(4, 'L''équipage d''un vaisseau découvre une capsule de sauvetage à la dérive dans l''espace depuis des siècles. Le contenu de cette capsule va les entraîner malgré eux sur la piste d''un des plus grands mystères de la galaxie : Xantah, l''astre de légende.'),
(5, 'Wrandrall cherche désespérément des compagnons de route pour sa quête : ils devront braver vents et marées pour aller explorer une grotte. Nul ne sait ce qui les attend sur cette route, ni ce qu''ils trouveront au fond de cette grotte… Une seule chose est sûre, c''est qu''ils n''ont aucune idée de ce dans quoi ils se sont embarqués.'),
(6, 'SURVIVAURE, une grande saga d''aventures spatiales démentielles, au delà des limites connues de l''espace. Ça se passe donc dans le futur, avec des vaisseaux qui font «wizzzz», des droïdes stupides qui font «bip» et des créatures extraterrestres qui auraient mieux fait de ne pas se commettre dans SURVIVAURE. De l''action, du suspense, de l''amour, du poulet, des crêpes au fromage, une quête sans merci, à lire chez vous sans chaussettes et mal rasé. La saga spatiale du millénaire : SURVIVAURE !!'),
(7, 'Une agence d''espionnage recrute l''Agent 0 et lui confie un gadget ultra-moderne pour mener à bien les missions dont il a la charge. Cependant, l''Agent 0 n''a pas les meilleures capacités en tant que membre de l''Agence. Un jour emprisonné, il est libéré par un adolescent sous condition de l''accompagner dans ses missions.'),
(8, 'Lucas Salpêtrière est un jeune homme à l''imagination débordante. Depuis qu''il est tout petit, il échappe à sa morne réalité quotidienne et à ses divers tracas (comme son boulot ou sa petite amie) en se réfugiant dans son monde imaginaire : Trimoria'),
(9, 'Alors que les cyber-technologies poursuivent leurs avancées, Une société scientifique du nom de Gamelife a réalisé un tour de force, que l’on croyait impossible jusqu’alors : connecter intégralement un humain a un monde virtuel, grâce aux travaux d’un éminent chercheur'),
(10, 'Le Chasseur est une fiction sonore en 21 épisodes publiés en temps réel. Elle s''intègre dans l''univers "Chroniques de la Terre Gelée" créé par Valkyria (a.k.a. Tristan Lohengrin) et François TJP'),
(11, 'A quel endroit vous réfugieriez vous dans le cas où le monde que vous connaissez ne soit plus un endroit sùr ? Si vous ne pouviez plus faire confiance à personne, si tant est qu''il y ait encore quelqu''un en vie ? Dans votre appartement ? C''est le choix que j''ai fait, et je ne le regrette pas, pour l''instant. Quand on trouve un dictaphone et qu''on est seul ... on fini par lui parler comme à son chat, ça occupe l''esprit.'),
(12, 'Super-Vilain et génie du mal en pleine dépression, le Docteur Bonobo est en mal de conquête mondiale et d''asservissement des peuples. Pour arriver à son but il s''est entouré d''une armée de clones (une de ses nombreuses créations), et de précieux alliés de tous horizons. Mais conquérir le monde n''est pas chose aisée et le Docteur l''apprendra à ses dépend durant sa quête de pouvoir.'),
(13, 'Deux frères pourfendeurs, chasseurs de monstres, les deux frères ne chassent pas comme des pourfendeurs lambdas, ils hypnotisent les monstres en chanson ...'),
(14, 'À qui m’entendrait, à qui voudrait m’entendre. Je sors difficilement de l’obscurité comme, comme on se réveille d’un trop long sommeil. Malgré mon crâne endolori et le battement incessant de mon coeur, quelques souvenirs reviennent... comme des flashs. Comme le veut la procédure, j’enregistre ce journal. Il permettra d’organiser les fragments de mémoire, les réminiscences vagues des évènements de ces derniers jours, ou semaines... Il arrivera peut être à expliquer ce que je ne parviens à comprendre. Comment j’en suis arrivé là. Comment je me retrouve condamné dans cette capsule de sauvetage. Dérivant indéfiniment dans le vide spatial. Comme une bouteille à la mer.'),
(15, 'une jeune étudiante se réveille après 8000 ans de cryogénisation dans un univers ou l''humanité n''a plus sa place '),

(16, 'Dans une galaxie en reconstruction, le capitaine Délisse, dernier homme vivant, survit en tant que convoyeur. Sur Seyten, une nouvelle mission lui est confiée par le grand Omgaa, caïd local. Amener des armes sur la planète Anef… Mais une jeune Néfil décide de s’inviter à bord du Belbeth System. Pour une raison bien particulière : sauver le capitaine d’un danger proche.'),
(17, 'Retrouver un journal de bord enfoui sous les mers ou perdu dans l''espace, donne un lien temporel unique avec son capitaine et ses péripéties. Il s''agit le plus souvent d''un lien vers le passé. Mais il arrive que l''on retrouve, par le biais de fictions, des journaux offrant un lien temporel avec le futur, ou du moins avec quelque chose qui y ressemble. C’est le cas des enregistrements audio du Docteur Ambrosia qui, depuis la station sous-marine Poséidôme, y a retranscrit ses activités avec la faune des profondeurs.'),
(18, 'Printemps de l''an de grâce 1680, John B., un pirate prétendument anglais, part à la recherche d’un mystérieux cacao après que sa prisonnière, l''experte en chocolat Philomène Ganache, lui a révélé son existence. Au cours de leurs aventures, ils se confrontent à de nombreux adversaires qui, tous, convoitent également ce cacao pour en percer le secret.'),



